version: '3..8'
services:
  movies:
    image: rahew/paytmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: rahew/paytmtrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: rahew/paytmmdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: rahew/paytmrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
